collections:
  posts:
    output: true
    permalink: /posts/:year/:slug
  archives: 
    output: true
    permalink: /:title
  destinations:
    output: true
    permalink: /:title
baseurl: ""
url: "midoandtolo.com"